### ISSUE TITLE
XNA Framework Redistributable 4.0 should use its Refresh version

### ISSUE THREAD

**Issue by chenyiping1995** [CNMan/MicrosoftHotfixesList#1]
Direct Download:
`https://download.microsoft.com/download/5/3/A/53A804C8-EC78-43CD-A0F0-2FB4D45603D3/xnafx40_redist.msi`

Information Page:
https://www.microsoft.com/en-us/download/details.aspx?id=27598

**Comment by CNMan** [comment]
thanks, fixed.
