### ISSUE TITLE
Problema su Windows Pos Ready 2009 con Windows Update KB4134651

### ISSUE THREAD

**Issue by damianofasoli** [CNMan/MicrosoftHotfixesList#4]
Un oggetto EXE ActiveX espone una classe COM con eventi (PippoAux.Connector)
ritornata come valore di ritorno di un metodo GetConnector di un'altra classe COM ActiveX del componente (PippoAux.AppConnector)

Durante la chiamata del client per ottenere la classe esce errore di run-time 430
Dim WithEvents pc As PippoAux.Connector

Private Sub Command1_Click()
Dim pcloc As Object
Dim pcc As PippoAux.AppConnector
Set pcc = New PippoAux.AppConnector
Set pcloc = pcc.Connect()
Set pc = pcloc ' HERE ERROR 430
pc.SayHello
Set pcc = Nothing
End Sub

Sembra sia necessario rimuovere l'aggiornamento tornando alla versione precedente di oleaut32.dll (8/10/2006)
Così viene ripristinato il funzionamento corretto

**Comment by CNMan** [comment]
if you mean patch's issue, please report it to microsoft.

**Comment by damianofasoli** [comment]
Thank you.
Does somebody know how to report patch issues to Microsoft?

Thank you very much
