### ISSUE TITLE
Windows XP missing some updates

### ISSUE THREAD

**Issue by vvb2060** [CNMan/MicrosoftHotfixesList#6]
下载并执行了2-14的脚本后，通过Windows Update MiniTool扫描发现缺少以下3个补丁：`kb2478971`，`kb2712808`，`kb975467`。其中`kb975467`存在于下载清单，但不在安装脚本中。另外两个补丁均不存在。
```
http://download.windowsupdate.com/msdownload/update/software/secu/2011/01/windowsxp-kb2478971-x86-chs_2cbba854d6ca81228e98a893214f624c2b0e25cb.exe

http://download.windowsupdate.com/msdownload/update/software/secu/2012/07/windowsxp-kb2712808-x86-chs_6b6c68337dad11f1a0389384925f95a48b706a61.exe
```

---
建议把1.reg改成0.reg并且不要建议使用，补丁并不能完全通用。
建议在事前关闭系统还原以加快补丁安装速度。
1.cmd
```
REG ADD "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\SystemRestore" /v DisableSR /t REG_DWORD /d 1 /f
```
---
在未重定向日志输出位置时，每个补丁都会在c:/windows/目录下产生一个日志文件。建议把参数改为` /q /z /n /o /log:nul`

**Comment by vvb2060** [comment]
全流程自动化脚本
```bat
IF EXIST "%CD%\5.net_1.1_install.cmd" REG ADD HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\RunOnce /f /v Update_5 /t REG_SZ /d "\"%CD%\5.net_1.1_install.cmd\"" && ECHO 成功添加 RunOnce。
SHUTDOWN -r -t 5 -c "即将重新启动计算机"
```
（dotnet实在太难等了

**Comment by vvb2060** [comment]
在安装VC++ 2010和VC++2013时，需要更新证书，否则验证失败无法安装。

这个是证书更新补丁 [WindowsXP-KB931125-rootsupd.zip](https://github.com/CNMan/MicrosoftHotfixesList/files/4479993/WindowsXP-KB931125-rootsupd.zip)

**Comment by CNMan** [comment]
我在虚拟机测试几次了（简体和繁体）都没有问题啊，是不是你没打注册表补丁导致的？

**Comment by vvb2060** [comment]
我是虚拟机全程断网安装的，快照后联网检查更新，然后恢复快照安装离线补丁。

**Comment by CNMan** [comment]
我是全程联网安装

**Comment by CNMan** [comment]
KB2478971 https://github.com/CNMan/MicrosoftHotfixesList/blob/9638c58163aace9255eb5cfee4e86556da13ba0d/windows_embedded_posready_2009/CatalogB.txt#L297
KB2712808 https://github.com/CNMan/MicrosoftHotfixesList/blob/9638c58163aace9255eb5cfee4e86556da13ba0d/windows_embedded_posready_2009/CatalogB.txt#L283
这两个有新补丁替换掉了

KB975467 这个可能跟KB968389这个补丁的安装顺序有关系，具体参考：http://support.microsoft.com/kb/975467
